source 'https://rubygems.org'

gem 'rails', '4.2.5'
gem 'pg', '~> 0.15'
gem 'sass-rails', '~> 5.0'
gem 'bootstrap-sass', '~> 3.3.6'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'haml'
gem 'simple_form'
gem "paperclip", "~> 5.0.0"
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'devise'

group :test do
  gem 'rspec-rails'
  gem 'factory_girl_rails'
end

group :development, :test do
  gem 'byebug'
  gem 'capybara'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
end
