Rails.application.routes.draw do

  root "posts#index" #


  #defined because there's no scaffolding for these.
  # there's no scaffolding because sessions don't need a database
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  # autogenerated because these were scaffolded
  resources :users
  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
