source 'https://rubygems.org'

gem 'rails', '4.2.6'
gem 'pg', '~> 0.15'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'paperclip'
gem 'bootstrap-sass'
gem 'factory_girl_rails'
gem 'devise'
gem 'dotenv-rails'
gem 'omniauth-facebook'
gem 'aws-sdk'
gem 'aws-sdk-v1'

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :test do
  gem 'byebug'
  gem 'rspec-rails'
  gem 'capybara'
  gem 'rspec-collection_matchers'
  gem 'shoulda-matchers'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
end

